#pragma once

namespace Physics
{

ref class RaycastHit;

/// <summary>
/// This interface allows subclasses to be alerted when a raycast report is 
/// generated by a raycast call.
/// </summary>
public interface class RaycastReport
{
public:
	/// <summary>
	/// Called when a ray intersects an object.  The information is provided by
	/// the RaycastHit class.  This function should return true to keep checking
	/// additional objects with the ray or false if enough objects have been checked.
	/// The RaycastHit object will only be valid for the duration of this function call.
	/// Shapes may not be returned in the order from closest to furthest.
	/// </summary>
	/// <remarks>
	/// SDK state should not be modified from within onHit(). In particular objects 
	/// should not be created or destroyed. If state modification is needed then the 
	/// changes should be stored to a buffer and performed after the raycast.
	/// </remarks>
	/// <param name="hit">The raycast hit with information about the raycast.</param>
	/// <returns>True to continue the raycase.</returns>
	bool onHit( RaycastHit^ hit );
};

}