void main( in float4 inPosition : POSITION0, 
		   in float4 inColor : COLOR0, 
		   in float2 inTexcoord : TEXCOORD0, 

		   const uniform float4x4 worldViewProj,	//The world view projection matrix

		   out float4 outPosition : POSITION, 
		   out float4 outColor : TEXCOORD0, 
		   out float2 outTexcoord : TEXCOORD1 )
{
	outPosition = mul(worldViewProj, inPosition);
	outColor = inColor;
	outTexcoord = inTexcoord;
}